export AWS_ACCESS_KEY_ID=$1
export AWS_SECRET_ACCESS_KEY=$2
export TALKTOME_OPEN_AI_TOKEN=$3
export TALKTOME_CONVERSATION_TABLE='Conversation'
export TALKTOME_USER_TABLE='User'
export TALKTOME_CONVERSATION_CLIP_BUCKET='talktome-conversation-audio-clips'
